### ISSUE TITLE
Sort out release management

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#100]
Currently we have to manually update several places in the code before we can do a release.

We should move the version numbering into our CI server which will make it much easier for us to do continuous deployment.

Since we aren't releasing as a library do we need to worry about setting the `package.json` and `project.clj` versions? I'm wondering because I think [newer] versions of node check the version is a real semver so we wouldn't be able to use a placeholder, so could we hardcode to 0.0.0 or something?

**Comment by darrenhaken** [comment]
You can use build tools to write these for you

**Comment by GentlemanHal** [comment]
@darrenhaken Thanks for the information, are there any particular tools you've used and could recommend?

**Comment by darrenhaken** [comment]
@GentlemanHal Something like https://github.com/vojtajina/grunt-bump works well.
I believe they'll be a grunt one too.

**Comment by GentlemanHal** [comment]
I've implemented this using the script I wrote. It's working but CI is changing a few files before it builds so technically it's not actually building exactly what you would have built locally.

We should probably find a cleaner way of doing this but I think what I've done is fine for now.

**Comment by GentlemanHal** [comment]
I've just realised my current approach is not actually correct Semantic Versioning. The PATCH number is just being set to the build pipeline number, but according to the spec

> Patch version MUST be reset to 0 when minor version is incremented.

So having an ever increasing PATCH number isn't actually allowed (which makes sense). So I'm reopening this so we can discuss what's the best approach.

**Comment by GentlemanHal** [comment]
Sounds like appending the build pipeline to the end might be the best approach:

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version

So for example the current staging release would become `0.8.0+498`

**Comment by GentlemanHal** [comment]
Decided to implement my above suggestion, adding the pipeline number as metadata to the version. Can be seen on staging now, let me know what you think.

**Comment by joejag** [comment]
+1 Better conforming.

On Tue, Jan 5, 2016 at 5:25 PM, Christopher Martin <notifications@github.com
