### ISSUE TITLE
Switch to ES6

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#102]
Use [Babel](https://babeljs.io/) to compile?

**Comment by GentlemanHal** [comment]
At what point should we consider this done? Once we've actually updated all the code?

**Comment by joejag** [comment]
I think we are there now. We are using Fat Arrows, String Interpolation, let/const and implicit functions.

Possible remaining, though not drastic improvements:

* https://github.com/lukehoban/es6features#modules
* https://github.com/lukehoban/es6features#promises

**Comment by GentlemanHal** [comment]
We are already uses promises throughout the code, I explicitly added this [promise library](https://www.npmjs.com/package/promise). This was because I switched to [fetch](https://github.com/github/fetch) and [localforage](https://github.com/mozilla/localForage).

I do get the feeling I've not added these correctly so they probably aren't getting polyfilled (i.e. we are probably using the library version even if a native impl exists), so its probably worth you taking a look.

**Comment by joejag** [comment]
Yeah, it should just be a case of dropping the lib.

I wish I had split this card into ES6 tooling and ES6 migration now.

After the promises can we say this is done?

**Comment by GentlemanHal** [comment]
If there is anything remaining that would require big changes, such as switching to proper classes, then we should do it now as part of this issue. As this allows us to add all the big bang changes to the same release making it easier for us to get back to adding features easier and hopefully releasing more frequently.

Do you think there are any more bigger changes remaining?

**Comment by joejag** [comment]
I read over the import rationale again, it's a better proposition once browser globals have all moved to support the same syntax. But it''s a more verbose and offers little benefit to use just now.

Example:

CommonJS (our current)
```
var lib = require('lib');
lib.someFunc();
```
becomes using ES6 syntax:

```
import * as lib from 'lib';
lib.someFunc();
```

Which is ugly to my eyes. Obviously I'm bike shedding as this appears to be the way JS is going, but I'd prefer if we skip using this feature just now.

**Comment by joejag** [comment]
@GentlemanHal I'm happy to take your lead with introducing classes around the React code. This article describes the difference: https://facebook.github.io/react/docs/reusable-components.html#es6-classes

**Comment by GentlemanHal** [comment]
@joejag Ok after doing some more reading I don't think we need to switch to real classes at this time. So if the promise stuff you mentioned is done I'm happy to close this issue.
