### ISSUE TITLE
Make adding trays more obvious

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#118]
This is really only an issue if some trays have already been added. New trays get added to the bottom of the list and if multiple trays (or a single tray with many projects) has been added then it's possible for the new tray to be added 'off screen'.

This means there is no obvious change on the screen and the user has to know to scroll the page to find the newly added tray. It should be more obvious a new tray has been added.

Suggestions:
- Automatically scroll the page to the newly added tray
- Add a info message under the trays on successful add (possibly with a link to scroll)

**Comment by achou8** [comment]
like the suggestions--made a quick animation for this interaction for reference. 

![addtray](https://cloud.githubusercontent.com/assets/7027103/15433715/7b2f402e-1e81-11e6-8754-a276707c01e2.gif)
