### ISSUE TITLE
"All projects" tracking option

### ISSUE THREAD

**Issue by jimmythompson** [build-canaries/nevergreen#129]
This is a result of the discussion coming out of #63.

The idea is to be able to choose whether to select projects to track in a given tray, or whether to skip that entirely and just watch the cc.xml. All interesting projects in the cc.xml would be displayed, and if a new build appears, one is deleted, or are renamed, it is immediately reflected on the monitor. Being on a team with rapidly changing builds, the maintenance (go up to the monitor, clicking refresh tray, clicking include all) makes it harder to convince people Nevergreen beats Jenkins Wall Display.

**Comment by jimmythompson** [comment]
Would this be on or off by default?

If the app didn't already have project selection, I'd have said on by default. I'd say selecting projects in a tray is an "advanced" feature. But because the app already comes with project select, I'd be tempted to say off by default.

**Comment by jimmythompson** [comment]
![ng](https://cloud.githubusercontent.com/assets/653864/12902270/160bd37e-ceb8-11e5-816d-80ee64fc093d.gif)

Seriously needs some UX love, any ideas?

**Comment by GentlemanHal** [comment]
Going to have to think about this a little more. I'm not happy with adding more toggles like that, but I'm not sure if there is a better alternative. Also it isn't particularly clear why "Track all projects" is different from "Include all", I guess you could name it "Track all current and future projects" or something.

I keep coming back to the idea of future projects. That seems like an important detail to highlight.

I also assumed this would be easier to implement, but I'm fairly sure it'll also require API changes. So maybe this isn't so different from #63 after all?

**Comment by GentlemanHal** [comment]
> Being on a team with rapidly changing builds, the maintenance (go up to the monitor, clicking refresh tray, clicking include all) makes it harder to convince people Nevergreen beats Jenkins Wall Display.

Also perhaps I've been solution blinded by #63. If the above is the core issue, do you think something like allowing remote configuration would be a good enough alternative? At least that way anyone could do it easier from their own browser without having to physically mess with the build machine.

**Comment by GentlemanHal** [comment]
Also if we add another toggle, refreshing the tray doesn't make sense anymore if you're tracking all, so that would need to be moved... This is definitely more complicated than I gave it credit for! :confused:

**Comment by jimmythompson** [comment]
> I also assumed this would be easier to implement, but I'm fairly sure it'll also require API changes. So maybe this isn't so different from #63 after all?

The API change I made on my fork basically says if the "include" key isn't in the request body then return all interesting projects. It doesn't break existing requests, if that helps.

> If the above is the core issue, do you think something like allowing remote configuration would be a good enough alternative?

I prefer a solution which means we don't have to keep updating the board, even if we can make it so I don't have have to get off my ass! :laughing: Remembering to update the board, and telling other people how to do it, isn't a big deal, but it's not the ideal.

**Comment by GentlemanHal** [comment]
> The API change I made on my fork basically says if the "include" key isn't in the request body then return all interesting projects. It doesn't break existing requests, if that helps.

This was my first thought as well, but then you wouldn't be able to exclude all projects for a tray. This probably isn't a common thing to do, but I can see it being useful in some situations. For example monitoring an external dependency only during an upgrade. 

Basically it feels like you could end up with some non obvious results if it isn't explicit.

> Remembering to update the board, and telling other people how to do it, isn't a big deal, but it's not the ideal.

That makes sense, I'm just wondering if complicating the UI more is worth it, given updating trays is trivial (IMO) at the moment. Will have to see if I can get some time from someone with more UX experience.

**Comment by GentlemanHal** [comment]
See #265 for some more context and discussion around this issue.

**Comment by GentlemanHal** [comment]
#63 has now been implemented via a simple setting that is enabled by default. As mentioned in the follow up comment on [#265 (point 3)](https://github.com/build-canaries/nevergreen/issues/265#issuecomment-456570724), this actually solves this issue as well.

For this reason I am going to close this issue as well, we can always re-open or create new issues if people get confused by this new behaviour and we need to change the UX.
