### ISSUE TITLE
Add a filter for projects in the tracking view (to make dealing with 100s of projects easier)

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#135]
If you have a tray that returns hundreds of projects it can be very tedious scrolling through the list to select the relevant projects.

### Only display the top level projects (and not stages)

I'm strongly apposed to this idea as we recently moved away from that approach to displaying stages. I think this is a better idea in general so would not want to move back to just dealing with the top level projects.

As a variation of this idea, we could just show the top level projects in the tracking view but still show the stage level on the monitor view. However this could get confusing and would stop people from being able to exclude some stages, which was the [original issue](https://github.com/build-canaries/nevergreen/issues/92) that prompted the whole project/stage revisit.

We could allow this to be a toggleable setting on the tray, but that feels like it's adding a lot of complexity to the UI for little gain, as even at the top level you could potentially still have hundreds of projects.

### Allow filtering

This would add an input box to the tray which would allow the list to be filtered in real time. Since we have technical users we could keep it simple by making it use regular expressions.

This seems like a nicer idea, but still has the issue of complicating the UI. It could potentially fit quite neatly floating right on the tray toolbar (where the show settings and refresh buttons live).

This could potentially still be quite tedious as you'd have to keep filtering and selecting, but it should be easier than scrolling to find the correct projects.

## Thoughts?

Are there any other options? What are peoples thoughts?

Raised by @brydoncheyney on Gitter

cc/ @build-canaries/owners

**Comment by darrenhaken** [comment]
I think the filter would be a good idea as it offers a lot of flexibility.

**Comment by brydoncheyney** [comment]
Apologies for the delay in responding...

I like the idea of a filter, obviously, but I think the UI impact is a legitimate concern.  For me, the pain when dealing with hundreds of projects is the initial setup - the endless scrolling through a list.  Even with judicious use of ctrl-f I found I still missed the occasional stage from a project.

Given an alternative approach to this resolution exists in #119 it may be that this would be a better route to take.  Once a Nevergreen instance is set up, the addition of subsequent projects si (relatively) trivial.  However, a new instance has a much greater impact as configuration may need to be created from scratch.

(Of course, a regex enabled filter would be superb...  I've mentioned [https://github.com/sanagrwl/balls](url) before, which uses this functionality)

**Comment by GentlemanHal** [comment]
@brydoncheyney Ok, we'll focus on getting issue #119 done before tackling this and I'll make this issue specifically for adding a filter.

If after both these changes are made you still have an issue just let us know!

**Comment by GentlemanHal** [comment]
@brydoncheyney Have added simple filtering, if you could check to see if it behaves how you'd expect I'd appreciate it.

Some questions for all:

I've added the filtering as component state. This means if you move to a different page or minimise the tray, your filtering will be reset. Would you expect any filtering to be persisted between pages?

Another thing to question is the behaviour of the include/exclude all buttons once the view is filtered. Currently they still act on the entire tray, including or excluding ALL projects. Should these buttons only work on the currently filtered subset? Should new buttons be added for this purpose?

(/cc @cowley05 @joejag )

**Comment by joejag** [comment]
I see it's a regular expression, rather than simple text contains. If I type '?' I get an error message for instance. Perhaps better off as simple project_name.to_string.includes?

I think the reset filter on page move is expected behaviour. When someone is adding projects it's a dedicated task, they add a bunch then view it. They aren't just flicking about parts of the UI.

The buttons question is difficult. There are a few options (it works on all, it works on a subset). I'd say visually disable them when the filter is present. It's less confusing then a button that mutates its use.

**Comment by GentlemanHal** [comment]
> I see it's a regular expression, rather than simple text contains. If I type '?' I get an error message for instance. Perhaps better off as simple project_name.to_string.includes?

Given how easy it was to get regular expressions working do you really think its worth switching to simple includes?

I guess it comes down to, are projects likely to include special characters (and thus having to escape them becomes tedious) or are teams more likely to want to do complex filtering (and thus having only includes becomes tedious)?

**Comment by GentlemanHal** [comment]
>  I'd say visually disable them when the filter is present

Done! Try it out and let me know if you still think this is the best idea.

**Comment by brydoncheyney** [comment]
currently on the last day of a holiday north (like, as north as you can get in the country, not 'north' like the types of @GentlemanHal consider) so will speak to the team when I'm back in civilization[1] next week... filter fix also sounds like it remove some confusion.  good call.

[1] I don't even have a phone signal most of the time. insanity.

**Comment by GentlemanHal** [comment]
@brydoncheyney you had a chance to check this out buddy?

**Comment by GentlemanHal** [comment]
I'm pretty happy with how this works, so I'm going to close this issue as it's the only thing holding back a new release!

We can raise new issues for any updates or changes.
