### ISSUE TITLE
Pipeline names that are separated with "." shows as one long name

### ISSUE THREAD

**Issue by cowley05** [build-canaries/nevergreen#137]
Because of this if you have a long pipeline name eg "abc.123.xyz.987" it causes the font scaler to put the name on one line in really small font.

Suggestion is to separate names that use a "." the same way as we do dashes, underscores and camel casing names.

Sentencising/splitting pipeline names that are separated with "." eg: xyz.123.abc would become "xyz 123 abc".

**Comment by GentlemanHal** [comment]
The problem with that is names with version numbers look strange. I guess it depends on what is more common, using a period as a word separator or using it as a useful character for delimiting version numbers and such like.

As an example, the apache cctray we use extensively for testing has a lot of version numbers.

**Comment by GentlemanHal** [comment]
You could probably check and not replace periods between two numbers?

"this.is.the.project.name.1.2.3" => "this is the project name 1.2.3"

**Comment by cowley05** [comment]
Yeah that's a good point @GentlemanHal i think that is a good idea to check between 2 numbers if we still think this is valuable?

I've seen a bunch of pipelines on a couple of projects which use dots as separators but also ones with versions.

**Comment by GentlemanHal** [comment]
@cowley05 I think we should do the extra check and not replace periods between 2 numbers. It's a little more complicated but it should work for both naming conventions.

We should probably raise an issue against clj-cctray as the change will be in that library.
