### ISSUE TITLE
Update project identifiers

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#140]
We should either, generate them from the web url or just remove them and use the web url directly.

Users would have to reselect projects if we make this change.

**Comment by GentlemanHal** [comment]
Snap and Go add the build labels into the URL so they change every time the pipeline is run 😞 

I've fixed it for now by using a regular expression to replace any build labels with 0, so matching can be done. I'm not entirely happy with this solution, but I think its better than generating random strings based on the name.

@build-canaries/owners thoughts?

**Comment by darrenhaken** [comment]
@GentlemanHal this looks good using the cc trays you gave me:
https://snap-ci.com/build-canaries/nevergreen/branch/master/cctray.xml

https://snap-ci.com/v9LRsSMg9YAhbPiPy6xe3XlcWO1sPjd1JyELNh697fE/cctray.xml

All looks like it's working to me so I'm going to close the issue. 
If you feel there's any other testing needed ping me and I'll look into it.
