### ISSUE TITLE
Make poll time configurable

### ISSUE THREAD

**Issue by ael1930** [build-canaries/nevergreen#141]
The feature existed before but after a chat on gitter it was removed due to concerns that someone may decrease the poll time to something like 1s and that would increase the load on nevergreen. It would be beneficial if it could be re-added with a with a lower limit of 5s.

**Comment by GentlemanHal** [comment]
This is working on staging but has a minor UX issue.

I've set the input to number which means you can use the little spinner or up/down arrows to change the value. Changing the value like this will correctly stop you going below the minimum value set on the input (5). However, you are able to manually type into the input and enter values less than the minimum. Chrome won't allow you to enter non numeric related characters (other browsers might), but you can still enter stuff like minus and e; so it's possible to enter completely broken values.

I've handled this simply by checking the value is numeric and valid (>=5) and if it's not, resetting it back to the default of 5, which means you can't actually break anything 👍 

BUT it does mean if you manually enter e.g. 2, the actual value set will be 5 but the UI won't update to reflex this. If you then change the page (to tracking for example) and then return to settings the value will now correctly reflex the actual value is 5 and not 2 👎 

I feel like this isn't a huge problem, so won't be fixing as part of this issue.
