### ISSUE TITLE
Switch to Redux

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#142]
https://github.com/reactjs/redux

Technically this doesn't have to be a breaking change, but to get the most benefit it's unlikely the store will be structured the same after updating. We could add a translation layer between the Redux store and the local storage, but this feels like it could get messy.

**Comment by GentlemanHal** [comment]
It turned out the store was organised very similar, so it was possible to add migration code that wasn't overly complicated.

**Comment by darrenhaken** [comment]
Tested this - looks good
