### ISSUE TITLE
Reset configuration

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#149]
Add a button to the Backup page that allows all the configuration to be reset back to the defaults.

**Comment by tharun208** [comment]
Hi @GentlemanHal, I am having a doubt with the reset button if we click on the reset button, it should clear the current configuration?

**Comment by GentlemanHal** [comment]
Hi @tharun208, this feature hasn't been implemented yet so are you asking because you want to submit a pull request?

There is a `delete configuration` button that is found on the `UnhandledError` page which will completely delete anything stored in local storage.

However, if you are seeing the `UnhandledError` then something has gone seriously wrong, so could you please open a new issue with as many details as possible as you've found some kind of bug.

**Comment by tharun208** [comment]
No, I am not getting UnhandledError and I want to implement this feature

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by GentlemanHal** [comment]
Ah, awesome you don't have a bug and more awesome that you want to contribute 😄 

You'll want to add a new section to the backup page "reset" that contains a warning paragraph similar to `UnhandledError` and deleting CI servers:

> Reset your Nevergreen configuration back to defaults. Please note, resetting your configuration can not be undone!

Then the simplest thing to do is make the reset configuration button clear the local storage and refresh the browser. This will force a reload from local storage which will now be empty and thus use all the defaults. If that is horrible UX we can think about doing something more complicated later.
