### ISSUE TITLE
Alternatives for clj-webdriver

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#162]
We use `clj-webdriver` for our functional tests and I just found out it is [unmaintained](https://groups.google.com/forum/#!topic/clj-webdriver/pwziJGyWj54).

This is unlikely to cause us any issues in the short term, but we should start considering alternatives before the tests end up failing because of an update to web/chrome driver etc.

**Comment by GentlemanHal** [comment]
- [ ] remove old functional tests
- [ ] add backup page to the test
- [ ] add monitor page to the test

**Comment by joejag** [comment]
I'm going to leave multiple trays as a future option. We've got parity with the Clojure functional tests now

**Comment by GentlemanHal** [comment]
> I'm going to leave multiple trays as a future option. We've got parity with the Clojure functional tests now

Makes sense, can you open a new issue so we don't forget please.
