### ISSUE TITLE
Contextual help

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#169]
It would be good to add more contextual help rather than having a completely separate help page.

We could add a ℹ️ type icon that when clicked expands some help text.

**Comment by cowley05** [comment]
nice idea!

I do think that the info on the help page is good such as the links to each cctray but i constantly switch between help and tracking to get them. This could be a good improvement to put it into the place where you need it.

Is there a specific place for everything and we can delete the help page?

**Comment by GentlemanHal** [comment]
We'd probably want to keep the help page for a couple of reasons. It's a good place for license and link info (the sections at the bottom in our current help page) and for completely new users, its a good place to go to get a general overview of everything.

Although for the last point we could implement #53 or have some kind of interactive tutorial that leads the user around the different pages.
