### ISSUE TITLE
Add syntax highlighting to the backup page

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#175]
Some investigation into the best library to use will need to be done.

Possible options:

- https://highlightjs.org/download/
- https://github.com/antonmedv/codejar#getting-started
- https://prismjs.com/

Whatever we pick we should lazy load it to avoid bloating the initial bundle.

**Comment by tharun208** [comment]
I like to work on this

**Comment by GentlemanHal** [comment]
This has been low priority for years, as users shouldn't be making massive edits to imports.
Given implementing this will just give us another feature to maintain I'm going to close this issue.
