### ISSUE TITLE
Add support for GitLab CI

### ISSUE THREAD

**Issue by EllaHolmes** [build-canaries/nevergreen#180]
[GitLab CI](https://about.gitlab.com/features/gitlab-ci-cd/)
[API docs](https://docs.gitlab.com/ee/api/pipelines.html#pipelines-api)

[Issue for adding cctray.xml support](https://gitlab.com/gitlab-org/gitlab-ce/issues/26858)

**Comment by GentlemanHal** [comment]
[GitLab panorama](https://github.com/joblift/gitlab-panorama) is a possible alternative (thanks @galan)

**Comment by GentlemanHal** [comment]
Given we can't action this I'm going to close.
