### ISSUE TITLE
Add support for Concourse

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#183]
[Concourse](https://github.com/concourse)

[Issue for adding cctray.xml support](https://github.com/concourse/concourse/issues/438)

**Comment by bamdadd** [comment]
+1

**Comment by BlacktoBlue** [comment]
Hi Guys,

I have created an API which will convert Concourse pipelines into CCtray.xml

have a look here: https://github.com/BlacktoBlue/ConcourseCCtray

please let me know any feedback.

**Comment by jzimermann** [comment]
Hello everyone,

Resuscitating this open issue to inform you that since release 5.x, concourse exposes `cc.xml`, as you can see [here](https://concourse-ci.org/observation.html).

Would you be able to now give support to `Concourse` as well?

Thanks

**Comment by GentlemanHal** [comment]
Hi @jzimermann, thanks for letting us know!

I get `not authorized` when I try and view the [example linked in the documentation.](http://ci.concourse-ci.org/api/v1/teams/main/cc.xml)

Do you have an example of what the XML looks like? I'm going to assume they add additional information into the name we need to parse out (like GoCD and CircleCI) to support it properly?

Also Nevergreen currently only supports basic auth, we have an issue to add OAuth support #249 but it won't be added for a while. So if basic auth isn't supported you'd still need to run some kind of proxy to allow Nevergreen to auth.

**Comment by jzimermann** [comment]
Hey @GentlemanHal 

Thanks for the quick reply. 

I actually did some more investigation and it turns out Concourse is expecting a cookie called `skymarshal_auth` that authorizes the request to proceed. I opened this [issue](https://github.com/concourse/concourse/issues/3979) on their repository to follow up on this matter.

If you're ok with that, I can close this issue. Let me know!

**Comment by BlacktoBlue** [comment]
Would it be possible to have nevergreen integrate with concourse 0Auth. So we wouldn't have to expose pipelines?

**Comment by GentlemanHal** [comment]
Hi @BlacktoBlue, thanks for the question!

> Also Nevergreen currently only supports basic auth, we have an issue to add OAuth support #249 but it won't be added for a while. So if basic auth isn't supported you'd still need to run some kind of proxy to allow Nevergreen to auth.

I don't really know what is required to support OAuth (as you can see our issue is empty!), so any help is much appreciated!

**Comment by GentlemanHal** [comment]
We really need to test this with a real CCTray XML generated by concourse.

If anyone is able to provide an anonymised one that would be really useful @bamdadd @BlacktoBlue @jzimermann ?

**Comment by GentlemanHal** [comment]
I'm going to close this.
Happy to re-open if someone can confirm if we need some CI specific parsing.
