### ISSUE TITLE
Frequent releases

### ISSUE THREAD

**Issue by arunvelsriram** [build-canaries/nevergreen#189]
Hi people. This is not a bug but a question.

[Latest release ](https://github.com/build-canaries/nevergreen/releases) was on Feb 1. Since then there are about 160 new commits (may contain a lot of features, UI and bug fixes I guess).

Is there any reason for not releasing changes frequently ?

**Comment by GentlemanHal** [comment]
Hi @arunvelsriram thanks for your question!

I would say it's a combination of a few reasons why we don't release more often, none of which specifically stop us from releasing regularly but combined have just had that side effect.

Nobody uses nevergreen.io, and honestly I wouldn't currently recommend they did as it is quite flaky  😞 We need to spend some time fixing up the infra code, but even then firewalls mean most teams need to run their own version inside their network. So most teams don't (or very rarely) upgrade once they have Nevergreen set up and running internally. 

So we decided that building bigger releases with more features would actually be better for convincing teams to upgrade as there is more likely to be something worth upgrading for.

It's quite rare people ask for new features they need immediately, but if that was the case it should (hopefully!) be simple for them to build themselves a jar directly from the source.

Also a few manual steps are involved in creating a release. None are that difficult or time consuming, and they could all probably be automated but automating them away isn't as fun as working on features.

**Comment by arunvelsriram** [comment]
Hi @GentlemanHal.

I agree that most teams host their own version of nevergreen due to security concerns.

My question was more about releasing JAR files frequently on GitHub releases page. Most teams may stuck with older version however, providing the latest version of jar file helps new (or may be all) users enjoy the latest features without having to build a jar from source. In other words amount of time a team spends to set up nevergreen will be less.

Thanks.

**Comment by GentlemanHal** [comment]
I've added a new issue to automate some more of the release process, https://github.com/build-canaries/nevergreen/issues/190
