### ISSUE TITLE
Nevergreen.io throwing unhandled exception after importing config

### ISSUE THREAD

**Issue by cisum-la** [build-canaries/nevergreen#223]
For bug reports please fill in as many of the following details as possible:

1. NeverGreen Website - https://nevergreen.io
3. which browser are you running in? e.g. `Chrome `
4. which CI server are you monitoring? e.g. `GoCD` 
5. steps to reproduce?

Go to https://nevergreen.io
Backup > import > locally> Copy and paste exported configruation
Go to "Monitor", it displays an exception in Cloud version
In locally hosted version it works fine and i see some failed pipelines as expected.
<img width="1625" alt="screen shot 2018-04-10 at 5 50 16 pm" src="https://user-images.githubusercontent.com/9635484/38590859-a0587fdc-3ce8-11e8-8b2f-408bd706a3b7.png">

**Comment by GentlemanHal** [comment]
Hi @cisum-la, thanks for submitting this bug report.

Did you export the configuration from the same version of Nevergreen? If you're able to anonymise the exported configuration and attach it to the issue that would be awesome. 

Exporting from nevergreen.io, and importing back into nevergreen.io (in a incognito window) worked OK for me.

**Comment by cisum-la** [comment]
I will get back regarding above questions in next 2-3 days as i need to take care of some other stuff.
I was thinking could the above issue be due to http within https, our internal GoCD servers are on http where as nevergreen.io is using https.

**Comment by GentlemanHal** [comment]
Hey @cisum-la, have you been able to test this again?

**Comment by GentlemanHal** [comment]
Hey @cisum-la, I'm going to close this issue for now as I wasn't able to reproduce.

If you have any additional information, please leave a comment and I can re-open if necessary.
