### ISSUE TITLE
Reduce logging by default

### ISSUE THREAD

**Issue by joejag** [build-canaries/nevergreen#224]
Currently, we log every request to Nevergreen as a `curl` command to ease debugging. That could contain sensitive information in the included trays. Let's turn the logging off by default, and make it enable-able via an environment variable.

**Comment by GentlemanHal** [comment]
As part of issue #221 I switched the logging to use [Logback](https://logback.qos.ch/).

So I'd suggest we update the default `logback.xml` configuration included in the jar to turn the curl logging off. If users self hosting want to turn it back on they can create a new configuration file and use `-Dlogback.configurationFile=/path/to/myfile.xml` to use that file.

**Comment by GentlemanHal** [comment]
I've done the following:

- Made the curl logging `debug`.
- Kept calls to a CI server at `info` level but redacted the following parts of the URL:
  - username
  - password
  - query values (as they are likely API tokens)
- Added an env var `LOG_LEVEL`, so the log level can be changed easily without having to provide an entirely new logback.xml file.

@joejag let me know if you think we should do anything else.
