### ISSUE TITLE
Filter jobs on the server

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#229]
Jobs are exclusive to GoCD and are run in parallel when the owning stage runs. This means you get a project for the stage plus another for each running job, and if anyone of them breaks the stage is also marked as broken. This all makes sense but the Nevergreen team felt it created too much noise on the monitor and generally just knowing a stage had broken was good enough, so we filter them out.

This filtering is currently done in the UI in both the Monitor and Tracking action creators. I think it would be simpler to do this on the server and would result in less data being sent back that just gets immediately ignored.

If we wanted to keep the API more flexible we could add a query parameter or something, although right now I don't think this is required.

**Comment by tharun208** [comment]
I like to work on this @GentlemanHal

**Comment by tharun208** [comment]
can you help me with this @GentlemanHal, we should need a query params to send the type of jobs to filter on the backend right?

**Comment by GentlemanHal** [comment]
Hi @tharun208, thanks for taking a look at this improvement!

After taking a look at the code to give you some advice, I don't actually think we need to bother doing this anymore. The UI code has already been refactored so we only have a single function that filters jobs.

So I'm actually going to close this issue, sorry if I wasted any of your time!
