### ISSUE TITLE
Full screen preview for success messages/images

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#230]

**Comment by ritik307** [comment]
@GentlemanHal Interesting issue... I would like to work on it. Can you kindly explain a little bit more on the feature like what's the existing UI looks like and how we want it to be?

**Comment by GentlemanHal** [comment]
@ritik307 thanks for asking about this feature! To be honest this is low priority so haven't really thought that much about how exactly it should work 🤔 

You can see the current success page at https://staging.nevergreen.io/settings/success

**Comment by GentlemanHal** [comment]
Low priority and unlikely to get worked on, so closing. Can always reopen in the future if we change our minds.
