### ISSUE TITLE
Improve system notifications

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#237]
Some ideas for improving system notifications:

- [x] Show a notification when a tray returns an error (e.g. Timeout)
- [x] Show a notification when a project starts building
- [x] Allow the user to select which notifications to show
- [x] Show a notification when a project is fixed

**Comment by GentlemanHal** [comment]
This requires some more thought. We filter projects on the server and we allow the user to select which projects are interesting.

To be able to correctly identify all project transitions we would need to return all projects and filter on the client. This however could result in a huge amount of additional data being sent between the client and server.

By default we only filter out healthy projects, so in that case we could assume missing projects are healthy. Which realistically is probably safe, but in theory they could have actually been removed from the server. However this approach no longer works if the filter has been changed to filter out more that one prognosis, and it also feels like the code could get quite messy.

**Comment by cowley05** [comment]
We discussed this issue and came up with these 3 options...
Were currently going with option 3 as its simplest to change and none of them are ideal.

![image](https://user-images.githubusercontent.com/1880175/197776273-385271f8-6d59-4d0f-9e22-505845434f13.png)
