### ISSUE TITLE
Timeout Retries

### ISSUE THREAD

**Issue by gpaul-idexx** [build-canaries/nevergreen#238]
We get the client reporting a timeout with some regularity, resulting in the alert sounding as if it's a failed build, but it's always a transient error and the next poll is good. It would be nice if there were some retries built in to avoid transient errors like this. Or, perhaps just not treat it as a build failure, treat it as something lesser - like a little notification banner that the server connection has been lost and it'll try to connect again.

**Comment by GentlemanHal** [comment]
Hi @gpaul-idexx, thanks for submitting this issue!

Is the timeout between the browser and the Nevergreen server, or between the Nevergreen server and the CI server?

Adding automatic retries for timeouts between the browser and the Nevergreen server should be fairly straightforward. Adding them between the Nevergreen server and the CI server is a little more complicated, as you have to make sure the browser doesn't timeout if the server is retrying (browser timeout = server timeout x server retries).

We could also potentially add more granularity around when sounds should be played, but this is more work.

**Comment by gpaul-idexx** [comment]
Hi, @GentlemanHal , thanks for getting back to me. As best I can tell, the timeout is between the browser and the Nevergreen server. I don't have a great way to tell, but I looked at the NeverGreen server logs and I didn't see an error related to a timeout in a call to the CI server.

**Comment by GentlemanHal** [comment]
Hi @gpaul-idexx, I've made a few changes and if possible it would be good to get some help testing them.

Firstly, I've updated the error messages and logging so it should be more obvious as to what is timing out. 

Secondly I've added a single retry to the UI code.

I tried playing around with adding retries to the server as well, but it started to get confusing and I had to massively increase the timeout on the UI which didn't feel right. So in the end I just added a single retry to the UI code as I'm a little worried adding more auto retries might introduce other problems (which hopefully issue #254 will fix)

So if you could try again, do see if this has made any difference that would be awesome. This isn't currently part of an official release so you'll need to either,

* use https://staging.nevergreen.io
* [build from source](https://github.com/build-canaries/nevergreen/wiki/contributing)
* [download the jar from CI](https://1078-26860954-gh.circle-artifacts.com/0/home/circleci/nevergreen/target/nevergreen-standalone.jar)

**Comment by gpaul-idexx** [comment]
Still getting red screens on the build monitor. When looking at the logs, I don't see any errors when nevergreen makes a request to our GoCD instance.

Generally, it's a 502 response on a POST to /api/projects/interesting

**Comment by GentlemanHal** [comment]
Oh no 😢 

To clarify, it sounds like you are seeing logs for the Nevergreen server hitting the GoCD server successfully, but the browser is getting a 502 response, is that correct?

502 is Bad Gateway so it does sound like a proxy or firewall or something is sitting in the way causing problems. 

Its also worth noting the UI won't automatically retry for a 502 response.
