### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by ritalinn** [build-canaries/nevergreen#241]
Hello. I am a volunteer. I want to give you a logo. What is your decision?

**Comment by GentlemanHal** [comment]
Hi @ritalinn, thanks for offering a logo!

We already have a logo, which can be found in our ["brand" repo](https://github.com/build-canaries/brand). Technically its a Build Canaries logo and not specific to Nevergreen, but I'm pretty happy with it for now.

That's not to say if you had some on brand ideas I wouldn't look at them 😉
