### ISSUE TITLE
Add support for OAuth authentication

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#249]
https://oauth.net/getting-started/

**Comment by GentlemanHal** [comment]
Pretty sure Nevergreen supporting bearer tokens is enough for most CI servers.

We realistically aren't going to implement any kind of SSO flows that require us to cache tokens or anything server side. So I think we can close this issue?

Would you agree with this @joejag @cowley05 ?

**Comment by joejag** [comment]
Yeah, wrong tech. OAuth is for humans to authenticate via delegation. CI Monitors use Access Keys for this.
