### ISSUE TITLE
Increase confidence for releases

### ISSUE THREAD

**Issue by joejag** [build-canaries/nevergreen#260]
Cypress type test. It needs to check:

* Handling error states from the server
* Switching between config tabs and back to the monitor page (can lead to monitoring breaking)
* Updating tray to a new URL (has broken breaks things in the past)

**Comment by GentlemanHal** [comment]
Using the [React Testing Library](https://github.com/testing-library/react-testing-library) will make our tests closer to how the user will interact with the page.

**Comment by joejag** [comment]
Closing as we moved to Typescript and react testing library
