### ISSUE TITLE
Add support for export/import to Gitlab snippets

### ISSUE THREAD

**Issue by joejag** [build-canaries/nevergreen#264]
## Feature Request

**What would you like to be able to do?**

Export and import config to Gitlab in the same manner as Github.

Support both gitlab.com and internal gitlab instances.

Snippets API: https://docs.gitlab.com/ee/api/project_snippets.html

API Examples:
```
http POST https://gitlab.com/api/v4/snippets?private_token=$PRIVATE_TOKEN \
    title="Nevegreen Config Backup" \
    file_name=nevergreen.json \
    visibility=public \
    content=@nevergreen-config.json

http GET https://gitlab.com/api/v4/snippets/$SNIPPET_ID/raw?private_token=$PRIVATE_TOKEN 

http PUT https://gitlab.com/api/v4/snippets/$SNIPPET_ID?private_token=$PRIVATE_TOKEN \
    title="Nevegreen Config Backup" \
    file_name=nevergreen.json \
    content=@nevergreen-config.json
```

# Remaining Tasks

Prod code:

- [x] Handle error messages from GitLab
- [x] Update schema to add new GitLab config
- [x] Allow custom hosts to be added to the CSP (similar to iframe)
- [x] Help text
- [x] Mobile styling (issue with tabs overflowing)

**Comment by GentlemanHal** [comment]
Just wondering out loud, is it worth moving the complexity to the server?

As in we provide a `/backup` (or whatever) endpoint that just takes the json and a `where` (or whatever) parameter.

```
POST /backup
{
    "where": "gitlab",
    "description": "Nevergreen backup",
    "content": {
        ...the json to backup...
    }
}
```

**Comment by GentlemanHal** [comment]
FYI, if we do it from the UI we'll need to update the `content security policy` `connect-src` to include gitlab.

**Comment by joejag** [comment]
It's also a bit worse than that @GentlemanHal as if we support internal GitLab servers we will need them to update the server to change the CSP

**Comment by GentlemanHal** [comment]
> It's also a bit worse than that @GentlemanHal as if we support internal GitLab servers we will need them to update the server to change the CSP

Oh, good point! This would be another advantage of having our own API.

**Comment by joejag** [comment]
Tested with GitLab official. 
Going to test with a hosted GitLab.

**Comment by joejag** [comment]
Tested with a hosted GitLab. All working.

We could improve things by pre-populating the available URLs given the environment variable provided by the user, but given [#271] will make the environment variable redudant I'd suggest we don't do this just now.
