### ISSUE TITLE
Allow user to set project sort order for the Monitor page

### ISSUE THREAD

**Issue by galan** [build-canaries/nevergreen#268]
## Bug report

**How are you running?**
`docker run -p 5000:5000 buildcanariesteam/nevergreen:3.0.0`

**Nevergreen version?**
v3.0.0+1393.ff97f79 Nintendo Red

**What are you running on?**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/71.0.3578.98 Chrome/71.0.3578.98 Safari/537.36

**Which CI server(s) are you monitoring?**
Self-build ccmenu server (might be open source soon)

**Expected behaviour?**
The list of failed ccmenu projects is sorted by name.
Optionally you might add an select-box to configure the order by name, last failed, natural, ..

**Actual behaviour?**
It is random (maybe order of the generated ccmenu resource, didn't tested).
Interestingly it is sorted in the tracking-tab.

**Steps to reproduce?**
1. Add a ccmenu resource that is not sorted

**Comment by galan** [comment]
Confirmed, the order of the projects in nevergreen comes from the order the resource provides.

**Comment by GentlemanHal** [comment]
Hi @galan, I'm going to reopen as I think a project sorting feature is a good idea and keeping this open in the backlog is the only way I'll remember and plan it in at some future point.
