### ISSUE TITLE
Auto-update dependencies in CircleCI

### ISSUE THREAD

**Issue by joejag** [build-canaries/nevergreen#270]
## Feature Request

**What would you like to be able to do?**

As a developer, it'd be great if non-breaking dependency updates were automatically applied via CI.

**What problem would it solve?**

Developer time.

**What do we need to do**

There's already an update script available at https://github.com/build-canaries/nevergreen/blob/master/.circleci/dependencies-upgrade.sh

It currently depends on running `pre-push.sh` to validate the update hasn't broken anything. However, that wasn't intended to be ran on CI. So we will need to discover another way of validating changes.

Once we have that we can set the job to run once a week and update all our Node and Clojure deps.

**Comment by GentlemanHal** [comment]
I'm going to close this for now as manually updating dependencies without breaking changes is pretty simple using tools like `npm-check-updates` and our `pre-push` script.

Happy to reopen if we want/need to look at this again in the future.
