### ISSUE TITLE
Drill down link to pipeline in jenkins

### ISSUE THREAD

**Issue by stumacsolutions** [build-canaries/nevergreen#273]
## Feature Request

**What would you like to be able to do?**
On the monitor tab within nevergreen it would be handy if it were possible to click on the build/pipeline and be taken straight through to Jenkins. This would effective be linking to the `webUrl` exposed by the cc.xml endpoint.

**What problem would it solve?**
This would save some time when navigating from nevergreen to jenkins in order to investigate a build failure or promote a pipeline to the next environment.

**Comment by GentlemanHal** [comment]
Hi @stumacsolutions, thanks for raising this feature request. This request has already been raised in #218, so I'm going to mark this request as a duplicate and close. Please subscribe to #218 for any updates.

Also if I've missed something and you feel your request isn't the same, just let us know and I can re-open!
