### ISSUE TITLE
Token based authentication

### ISSUE THREAD

**Issue by jainsahab** [build-canaries/nevergreen#285]
## Feature Request

**What would you like to be able to do?**
Introducing access-token based authentication in nevergreen.

**What problem would it solve?**
For some CI/CD tools where Oauth is configured, it is not possible to configure nevergreen with a set of credentials. Fortunately, some of them provide Access token-based authentication. For Ex: [GoCD](https://docs.gocd.org/current/configuration/access_tokens.html). We can generate a personal access token and configure nevergreen with it.

**Comment by GentlemanHal** [comment]
Hi @jainsahab , thanks for raising this issue and submitting a pull request! 🎉 

Hopefully I'll get some time to review and merge this week[end] 😄

**Comment by expertisee** [comment]
Introducing simple way to build Token based authentication application. User input details pass to the API and returned generated token. 

```
const loginDetails:LoginDetails = {     
      UserEmail: this.userLoginEmail,
      Password: this.userLoginPassword
    };

    this.loginService.ValidateLogin(loginDetails).subscribe(
      result => {
        console.log("Validate login details");
        console.log(result);
        if(result['UserId'] == 'INVAILD')
        {
          this.message = "INVAILD";
        }
        else {
          this.message = "SUCCESS";
        }
      }
    );

```
After generated token it is coming to front end. You can also refer [them ](https://expertiseexchange.com/#/MasterPageComponent/TopicDetails/11)for a more complete solution.
