### ISSUE TITLE
Different color for aborted status

### ISSUE THREAD

**Issue by nningego** [build-canaries/nevergreen#287]
## Feature Request

**What would you like to be able to do?**
I would like to differentiate aborted builds from failed builds

**What problem would it solve?**
- It helps get quicker feedback on failure. Which prompts faster or slower response when aborted versus failed.
- Jenkins manual input step unfortunately only provides sucess or abort https://jenkins.io/doc/pipeline/steps/pipeline-input-step/) - which misleadingly shows up as failed on the entire pipeline. It would be nice to know the difference since they mean different things. 

And yes, we should be actively solving all problems that cause the build to be not green. But different colors for different statuses help quickly understand what might have happened.

**Comment by nningego** [comment]
Correction. Jenkins returns aborted builds as 'Failure'. So I suppose only bullet point 1 applies.

**Comment by GentlemanHal** [comment]
Hi @nningego, thanks for raising this feature request!

Unfortunately I don't think we are going to be able to implement this feature 😞 

Nevergreen only integrates with the [CCTray XML format](https://cctray.org/v1/) as it is the defacto standard and thus allows us to monitor many different CI servers.

However the spec is over a decade old and doesn't really contain a lot of the information more modern CI servers provide if you used their APIs directly. For example the spec only has `Success, Failure, Exception, Unknown` as valid statuses.

If you can provide an (anonymised) copy of the CCTray XML file that has aborted builds I'm happy to take a look to see if we can figure out the difference between aborted and failed.

**Comment by GentlemanHal** [comment]
I'm going to close this under the assumption we can't actually do anything about this (short of integrating directly with the Jenkins API which isn't happening anytime soon / ever)

@nningego if you are able to provide a CCTray XML with aborted builds I'll still happily take a look and reopen if there is something we can do.
