### ISSUE TITLE
All projects marked as new on first refresh after opening Nevergreen

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#290]
## Bug report

**How are you running?**
nevergreen.io

**Nevergreen version?**
v4.0.0+1882.fa07b87 Orange Soda

**What are you running on?**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

**Which CI server(s) are you monitoring?**
Doesn't matter.

**Expected behaviour?**
Only new projects since the last refresh are marked as new.

**Actual behaviour?**
All projects are marked as new.

This is because the `seen` API attribute is empty on the first refresh, and this is because we don't actually save the `trayId` against the projects in local storage... 😞 

**Steps to reproduce?**
1. Load Nevergreen (or reload the page if already loaded)
2. Refresh any added CI server
3. All projects will be marked a new

**Comment by chadlwilson** [comment]
Is this possibly the reason that we appear to be losing our include/exclude filter settings on a browser/machine restart?

The behaviour we observe is that the `monitor` screen becomes "unfiltered" on opening the browser on Nevergreen; i.e it loses our earlier exclusions. When navigating to the `tracking` tab the settings _look_ correct (as they were before restarting the machine/browser), however upon clicking "Refresh" manually, all of the previous filter settings are lost, and everything becomes "New".

**Comment by GentlemanHal** [comment]
Hi @chadlwilson, yeah I think this is related (unless the `automatically include new projects` setting is false...)

We plan on releasing v5.0.0 very soon, so if you are still having issues afterwards can you please open a new issue.

Also I think you'll probably need to refresh and reselect all the correct projects to make sure the local storage is updated correctly, sorry! 😞

**Comment by chadlwilson** [comment]
Thanks @GentlemanHal! Looking forward to `5.0.0` :-)

**Comment by GentlemanHal** [comment]
@chadlwilson v5.0.0 has now been released!
