### ISSUE TITLE
Smart help page

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#297]
## Feature Request

**What would you like to be able to do?**
Replace the inline contextual help with a "smart" help page.

This would be accessible from the top nav menu and by pressing the `?` keyboard shortcut. By default it would open a model with the help for the current page. 

It would also include a search box allowing the user to search for any help 'articles' that existed.

**What problem would it solve?**
Originally we had a single help page accessible from the top nav menu. This page contained all the help and used sections (like added CI servers have) to separate the help for different pages. This made the page bloated and there was quite a big disconnect between the help and the actual page or settings being explained.

We replaced this help page with contextual inline help, which was meant to fix some of these problems. However it introduced some new problems, styling the button to be in the correct place can get quite complicated and having a contextual help button next to multiple settings turned out to look very messy. So for example the add CI server contextual help also explains the CI server specific settings which can be changed once a CI server is added.

**Comment by tharun208** [comment]
Hi @GentlemanHal, I like to work on this and also is there any preferred UX for this feature?

**Comment by GentlemanHal** [comment]
Hi @tharun208, this feature isn't ready to pick up yet. I only raised it a few days ago and haven't really thought exactly how I'd like the UX to work, and it'll probably involve trying some things out.

This is also quite a big feature that involves changing almost every page. I don't want to discourage you from contributing but I'd prefer this not to be picked up right now.
