### ISSUE TITLE
Include/exclude all projects is noticeably slow when a feed has lots of projects

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#304]
## Bug report

**Expected behaviour?**
All projects should be included or excluded without any delay.

**Actual behaviour?**
All projects are included or excluded with a noticeable delay.

**Steps to reproduce?**
1. Add a feed with lots of projects (mine has ~140 projects)
2. Click the "exclude all" button

This is because it loops through all projects and triggers an include/exclude action on each one. We should add an explicit include/exclude all action.

**Comment by cksharma11** [comment]
Hi @GentlemanHal 

Can you review my PR?
