### ISSUE TITLE
Display first line of exceptions back to the user

### ISSUE THREAD

**Issue by joejag** [build-canaries/nevergreen#31]
Differentiate from user error 4xx and server error 5xx.

This can be used to tidy up #30

**Comment by cowley05** [comment]
This is implemented already but the wrong div ids are being used i will fix and style as best i can might need a touch of @mrgeorgegray to sort out styling i will let you know...

**Comment by cowley05** [comment]
looks like this is done unless you guys wanted a more specific error to show? but it looks fine to me for now? the divs got fixed with joes push and the error appends correctly now

**Comment by GentlemanHal** [comment]
Seems to be working fine for me now, we might want to style the errors a little nicer but that can be done as part of general styling and refactoring.

Am going to close this for now, feel free to open it again if there are any problems.
