### ISSUE TITLE
New UI: Config screen update for DesertSand

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#33]
Should we add all other options (e.g. #9, #24) to an "advanced config" section that is collapsed by default?

For example, where the current `success text` label is would be replaced by an `advanced` label of some kind which once clicked slides open to reveal the other options.

I'll try and attach a mock up of the idea tomorrow.

**Comment by GentlemanHal** [comment]
@mrgeorgegray  I've assigned you so you can use this for the initial updates of the config screen

**Comment by mrgeorgegray** [comment]
@GentlemanHal nice one. Made a start yesterday with HTML markup, still got a fair bit of CSS to do and then can review. Joe and I also discussed a way that further down the line you'd be able to incorporate multiple CC Trays within the dashboard.

**Comment by joejag** [comment]
@GentlemanHal @cowley05 you can see the UI concept @mrgeorgegray has designed here: http://staging.nevergreen.io/dashboard.html

We should move the current config screen to use this iteration then do a release.

We can tackle #45 after that. What do you guys think?

**Comment by GentlemanHal** [comment]
:+1:

**Comment by joejag** [comment]
^^^ staging dashboard is now using new UI

**Comment by cowley05** [comment]
Is this issue still open?

**Comment by GentlemanHal** [comment]
@cowley05 There are still things missing, like the version number and comments like "All the smallprint can go here." that should be fixed before we close this.

**Comment by GentlemanHal** [comment]
Things we should fix before closing this, mostly a list for when I hopefully pair with @mrgeorgegray this week.

* The version in the footer (I've added it but it can probably be made to look nicer).
* Make the tracker tab have scroll bars instead of the whole page so the footer stays fixed.
* Get rid of the green highlights on buttons etc!
* Make sure the check boxes work in other browsers (something George mentioned).
* Can we make the tracker tab use all the space like the main monitor does? i.e. Have multiple columns while there is only one tray.
* Make the "go to monitor page" button more obvious.
* Remove the save button from the success page or add save buttons to the other pages (should be consistent).

**Comment by cowley05** [comment]
I did the following:
* tested checkboxes - These dont work in safari but in firefox they are fine
* removed highlighting on all buttons when clicking them
