### ISSUE TITLE
Shortcut to mute notifications

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#331]
## Feature Request

**What would you like to be able to do?**
Quickly mute audio notifications from the Monitor page.

**What problem would it solve?**
This would allow people to easily mute audio notifications for a short time if they were in a meeting or something without needing to actually mess with settings.

I was thinking initially this could just be a keyboard shortcut. The `space` key might be a good choice as the `m` key is already used to navigate to the Monitor page.

**Comment by thesheps** [comment]
Do we think we'd want this to be on a configurable timeout, or just a spacebar toggle?

**Comment by GentlemanHal** [comment]
I was thinking just a spacebar toggle to keep it simple.

Possibly with an overlayed "mute" icon, although this could be added under a different improvement "issue" (I really hate this are called issues on GitHub 😢)
