### ISSUE TITLE
Add an alternative to colours to distinguish between prognosis

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#341]
## Feature Request

**What would you like to be able to do?**
Add some other kind of identifier for prognosis on the Monitor page.
This could be an icon, or some kind of background pattern.

**What problem would it solve?**
This would make the page more accessible.

**Comment by thesheps** [comment]
I was doing a bit of research on this as I vaguely remember someone talking about this at a con I went to a few years back! Could always look to see if [patterns.css](https://github.com/iros/patternfills/blob/master/public/patterns.css) could fit the bill as an alternative to colouring, and include an option for build iconography too?

**Comment by GentlemanHal** [comment]
Looks interesting, but using a library is possibly overkill for what we need. We have 5 prognosis we need to distinguish between, so writing our own CSS might be easier for tweaking etc. Can certainly base it off existing patterns / CSS!

I certainly would like more research on this, I'm far from an accessibility expert and I don't have any colour blindness issues. So it's hard for me to know what would actually be beneficial for people 😖 

We also have #196 which is related and might be enough to not need this?

**Comment by GentlemanHal** [comment]
I was recently playing a card game that used [ColorADD](https://www.coloradd.net/en/). I'm not sure how much traction its gained, but obviously some as it was being used in the card game. I've not seen any other standards like this, so think it could be a good fit for our use.

Looks like it isn't free to use, will reach out to them to see what we can do as an open source project.

**Comment by GentlemanHal** [comment]
I've decided the icons and text, along with being able to change the colours is enough for to close this issue.
We can always improve in the future, but we'd probably need some expert help to know how to do that.
