### ISSUE TITLE
Cache busting for releases

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#48]
We currently output the same file for our JavaScript and CSS, could this result in having caching issues when we release new versions?

**Comment by joejag** [comment]
I don't think having one file affects caching. Still a possible issue.

We should add a Header Expires and ETag to force the client to check.

**Comment by GentlemanHal** [comment]
That sounds like the sort of thing we don't want to be doing manually?

**Comment by joejag** [comment]
Yeah, we'd want some clojure middleware library, or jetty thing to do it
for us

**Comment by GentlemanHal** [comment]
I'm thinking we should just add a simple no cache header for now. As by the nature of the app it's going to get loaded once and then probably left refreshing via ajax for ages. This would at least mean we don't run into issue with people using old cached versions on nevergreen.io

`cache-control: private, max-age=0, no-cache`

We can worry about adding more complicated caching later then?

**Comment by joejag** [comment]
:+1:

**Comment by joejag** [comment]
Yay for no cache

**Comment by joejag** [comment]
(testing Gittr)
