### ISSUE TITLE
Add a helpful dialog that tells people where the usual cctray location is

### ISSUE THREAD

**Issue by joejag** [build-canaries/nevergreen#49]
On the 'tracking - config' page if the url is blank, we should render a box of the usual cctray locations. We can put this text where we currently show the projects and the include/exclude all buttons.

We should hide the include/exclude buttons until the URL is added

The list of usual locations can be found on our README.

**Comment by joejag** [comment]
I've committed the code for this. It'd be great is @mrgeorgegray could take a look at the styling.

You can see it at http://staging.nevergreen.io/config. If you remove your existing cctray url you'll see the text.

**Comment by GentlemanHal** [comment]
Closing this as it works nicely for now and we will probably switch to a simple overlay the first time someone loads Nevergreen.
