### ISSUE TITLE
Show a thumbnail preview for success messages that are images

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#55]
The styling would need to be done in such a way that a mix of success images and messages still looks ok.

Perhaps success messages could use an icon for the thumbnail?

@mrgeorgegray Any thoughts?

**Comment by cowley05** [comment]
I agree i think the screen could look good if we used the inputs as they are for messages, 
but for images we could use the original thing george said with the thumbnail box, with the plus inside of it. this could just sit under the messages and as you add one it becomes thumbnail then a new one apears next to it etc. ill upload a sketch :)

**Comment by GentlemanHal** [comment]
Not sure I follow, you might need to add multiple diagrams to show the flow. Do you want to have separate buttons for adding images and messages? 

If so, I'm not keen on that idea, perhaps something like this could work?

* You add a new message using the new button (as you do now).
* If you enter a success message into the input box.
  * It just remains in the list (as it does now)
* If you enter a image url.
  * This gets previewed in a thumbnail which appears under all the success messages.
  * The message input box you added the image url to disappears.
* If you add more images they appear next to the other added images in a row like a thumbnail gallery.
* You can remove images by click an X or something on them that appear

**Comment by GentlemanHal** [comment]
Outstanding changes:

* Force the width and height of images so they have the same ratio and scaling mode as they'll get when applied to the monitor section. This will allow a more realistic preview and highlight if people try and used 'strange' sized images
* Style the remove button to look less ugly (perhaps show a simple cross on top of the images in the corner)
* Don't show empty sections

**Comment by cowley05** [comment]
Do we think this can be released now? or does anyone have other ideas for remove button?
