### ISSUE TITLE
Add client side validation to tracking section

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#60]
If the user tries to input a url that doesn't start with http or https we should show them an error. We could also add validation if someone enters a username or password but not both.

The errors could be pretty standard, make the box red and add a message somewhere.

**Comment by GentlemanHal** [comment]
Changing this issue to adding client side validation for urls etc as this seems like a better idea than changing what people input.

**Comment by jimmythompson** [comment]
Went to look at this today, apparently this is already in place. Is there something I'm missing, or can this be closed?

<img width="1106" alt="screen shot 2015-12-20 at 16 00 27" src="https://cloud.githubusercontent.com/assets/653864/11918672/dba662be-a732-11e5-8cbe-f01261befbd8.png">

**Comment by GentlemanHal** [comment]
This should have been assigned to me, as I added some simple validation. More complicated validation has not been added yet, was contemplating whether we really needed it or not (see below). 

I initially added validation for the import feature, then expanded it to other areas. I think I've accidentally committed everything against that issue number, which is why it looks like nothing was done for this issue!

The main bit of more complicated validation is, entering a username OR password (or visa versa) but not both. This isn't supported by validate.js out of the box, feel free to have a go at implementing as I still need to finish off issue #64

**Comment by joejag** [comment]
I'm thinking through the UX. Is it if either of us/pw are present and the other isn't then show invalid?

Cross-field validation is always a bit manual

**Comment by joejag** [comment]
The invalid URL message comes from the Clojure code:

https://github.com/build-canaries/nevergreen/blob/master/src/nevergreen/api/projects.clj#L27-27

**Comment by joejag** [comment]
Hmm, what if the password or username is blank? That could be a valid entry

**Comment by GentlemanHal** [comment]
The picture @jimmythompson linked is definitely coming from the JavaScript code:

https://github.com/build-canaries/nevergreen/blob/master/src/js/actions/TrayActions.js#L24-L27

Entering a username with no password or a password with no username doesn't seem like it would ever be valid?

**Comment by joejag** [comment]
Ah yes! I was searching for the error message and only saw it in the Clojure code.

I had in my mind that mysql has a blank root password by default. Since we can't say for sure what any cctray.xml supporting server may require. That said, i suppose it's going to be a mistake 99.99% of the time if you skip one of the us/pw combo

**Comment by jimmythompson** [comment]
> Entering a username with no password or a password with no username doesn't seem like it would ever be valid?

> That said, i suppose it's going to be a mistake 99.99% of the time if you skip one of the us/pw combo

Could go with this assumption and see if you receive any feedback stating otherwise. I can imagine a dystopian situation where you'd have authentication with a blank password, but as that defeats the point of authentication in the first place, I'd expect it's _extremely_ rare.

**Comment by GentlemanHal** [comment]
Hmm, good point. I agree it seems extremely rare, but given it requires us doing work which could potentially block someone with a legitimate use case, I'm now thinking we should **not** add the extra validation.

We can do the reverse and add the validation if we get a bunch of issues about adding trays being confusing or difficult.

We might want to recheck the server side validation and make sure any errors coming back are as helpful as possible, I think at the moment you might just get a fairly generic server error back. I know we tried to make it clear as to whether the Nevergreen server or the CI server was throwing the error I'm just not sure if it's at a granular enough level to tell why the CI server rejected the request. Probably worth spinning this into it's own issue?

**Comment by joejag** [comment]
I added a fake server to the ```develop.sh``` so we can test secured servers locally

If you hit ```http://localhost:5050/secure/cctray.xml``` the username is 'u' and password it 'p'.

You can see currently if there is any problem with the credentials then we just display "Server Error" which isn't great. I assume there's a decent HTTP error code being returned from the server which we could show the customer

**Comment by joejag** [comment]
I'd suggest not adding the JS validation, and instead improve the error message being sent by the backend server.

In general though, the journey for this isn't great since you cannot re-enter a us/pw, you have to add it as a new tray.

**Comment by GentlemanHal** [comment]
@joejag issue #90 has been created for updating username/password of existing trays, and it's been added to the 0.9.0 release already :smile:

**Comment by GentlemanHal** [comment]
I'm happy this is done now, if someone (@joejag, @cowley05) could QA and close that would be tippy top!

**Comment by joejag** [comment]
QA'd. Much better
