### ISSUE TITLE
Show stage name underneath pipeline name

### ISSUE THREAD

**Issue by cowley05** [build-canaries/nevergreen#62]
This would obviously only be for CI which have this of course, which i think may only be Go???

**Comment by GentlemanHal** [comment]
Snap also has the concept of stages. See [clj-cctray README](https://github.com/build-canaries/clj-cctray) for a complete list of keys currently returned.

This should be an optional feature that is turned off by default. The ideal place for this would be the cctrays "option panel" which hasn't been implemented yet as we haven't introduced multiple trays (issue #37).

**Comment by cowley05** [comment]
Good point chris should be configurable!

**Comment by cowley05** [comment]
Think this is done now guys, can someone QA please...

**Comment by GentlemanHal** [comment]
The stage name displayed is incorrect but this is an issue with clj-cctray, an issue has been opened to fix that.

This looks good and shouldn't require any more changes so closing for now.
