### ISSUE TITLE
Automatically add new projects

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#63]
This should be a configurable option (off by default?) that allows new projects added since Nevergreen was configured to be automatically added to the monitor view.

This would stop people needing to manually configure the view every time a project is renamed or added.

We would need to start sending the seen projects to the server on every request to allow it to work out which projects are new.

**Comment by joejag** [comment]
I would rather have it on by default. Removing extra info seems preferable to adding missing info.

Very context specific. So will need to be configurable.

**Comment by joejag** [comment]
Now thinking 'on' by default

**Comment by jimmythompson** [comment]
This would really help out my team. We're making new services (and jobs) almost weekly, the problem isn't as bad as it was before you could refresh a tray, but it's a pain point nonetheless.

We use Jenkins and share it with other teams, however Jenkins provides a cc.xml for individual views, so the ideal, for me, would be a "simple" or "dumb" tracking option. No toggles, everything in the CC.xml is checked and interesting builds displayed.

**Comment by GentlemanHal** [comment]
The initial idea is non-trivial and would require changes to both the UI and server. 

Your idea seems like it would be a bit simpler to implement, so I suggest we create a new issue for that so we can prioritise it into a release.

They do seem like different use cases as well, this issue is more for established projects that have few changes to CI and thus when they do happen people are likely to forget to update Nevergreen. Your issue sounds more useful for new projects that are making lot's of changes to CI and don't want to worry about updating Nevergreen until the changes stabilize.

**Comment by darrenhaken** [comment]
👍

**Comment by GentlemanHal** [comment]
See #265 for some more context and discussion around this issue.
