### ISSUE TITLE
Export configuration

### ISSUE THREAD

**Issue by joejag** [build-canaries/nevergreen#64]
We want to run the same build monitor twice across sites.

```javascript
dump = JSON.stringify(localStorage)
localStorage = JSON.parse(dump)
```

We could make this a bit nicer by having a dialog that appears with this base64'd, then having an import dialog available as well.

**Comment by GentlemanHal** [comment]
I think we should use this issue to allow clean up the configuration in general and handle migration of configuration nicely.

**Comment by joejag** [comment]
What remains to be completed for this task?

**Comment by GentlemanHal** [comment]
The main thing remaining is cleaning up the validation code to make sure valid json is being imported.

It would also be good to get a general review of the whole area as quite a lot has changed and we really should try and get to a point where we can easily start migrating configuration instead of releasing breaking changes.

**Comment by joejag** [comment]
QA'd a fair bit. Tried normal import/export, hacking the JSON to make it invalid (catch badly copied JSON). All looks good.

The success messages look like they are in their twice:

```
 "success": {
    "messages": [
      "=(^.^)="
    ]
  },
.......
"messages": [
    "=(^.^)=",
    "asdasd" 
  ]
```

Is that expected?

**Comment by GentlemanHal** [comment]
@joejag The export is just loading all the keys stored in the Nevergreen 'namespace'.

```
"messages": [
    "=(^.^)=",
    "asdasd" 
  ]
```

Is the original way messages were stored and is no longer used. If you manually clear your local storage and check again you, that entry should no longer exist.

**Comment by joejag** [comment]
Cool, happy to close this issue
