### ISSUE TITLE
Allow spaces in success message so messages like ( ˘ ³˘)♥ can be used

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#65]
Some other characters from [Disapproval Look](http://www.disapprovallook.com/) also don' work :cry: 

This is most likely an issue with ScaleText and non standard characters.

**Comment by joejag** [comment]
It has spaces in it right? We break on spaces

**Comment by GentlemanHal** [comment]
Oh yeah I didn't notice them at all! 

Some of the faces are awesome and should be useable! I wonder if we can allow escaped spaces in some way?
