### ISSUE TITLE
Show info of who triggered/broke the build

### ISSUE THREAD

**Issue by cowley05** [build-canaries/nevergreen#66]
This info would probably come from the git repository and be configured in a tab in the app.

**Comment by GentlemanHal** [comment]
This would involve integration with git to get accurate info, so is very unlikely to happen anytime soon.

**Comment by GentlemanHal** [comment]
I'm going to close this as we are never going to integrate with git repositories and even if we wanted to start using CI specific APIs, that would probably be done as proxies that output a CCTray XML file.
