### ISSUE TITLE
Send notification to slack

### ISSUE THREAD

**Issue by cowley05** [build-canaries/nevergreen#67]
Not sure if we want nevergreen to go in that direction or not?
*Requested by web team.*

**Comment by joejag** [comment]
Hmmm..... you'd really want that stuff coming from your CI server, since it's the golden source or that info. Is this difficult to do in most CI Servers to the point that it's be a feature worth adding for our customers?

**Comment by GentlemanHal** [comment]
I agree with @joejag this doesn't seem like something Nevergreen should be doing.

Perhaps if you were using it to aggregate many different CI servers from multiple teams and you didn't want to mess about managing them all separately?

Certainly something to consider but I don't think its high priority.

**Comment by cowley05** [comment]
Kind of thought the same whilst writing that issue haha and mansi said the same, just thought it worth putting it out there. will close and forget.... :)
