### ISSUE TITLE
Add an endpoint that redirects to the latest release on github

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#73]
That way all our documentation and Docker image can have a consistent url and only the core Nevergreen app needs to update when a new release is published.

**Comment by joejag** [comment]
There is this: https://github.com/build-canaries/nevergreen/releases/latest

It's not ideal as it just redirects to the release page. We could parse the HTML (lame). 

What other approaches do we have? updating something manually?

**Comment by GentlemanHal** [comment]
Parsing the html sounds pretty clunky and error prone.

We already have to manually update a few places in the repo so having one more sounds like a nicer idea than trying to use that github url.

If we want to minimise manually updating, I'd rather invest the time in writing some kind of script that replaces the version numbers for us in the correct files.
