### ISSUE TITLE
Can we remove the timing page?

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#75]
Is configuring the polling time really required?

I'll admit the main reason I don't like it is because it's an entire section for a single field, but it got me thinking does it matter to a user?

If you want a better reason, it allows the users to put 5x the load on the server by setting it to 1 second, and they have no incentive not to do so.

**Comment by joejag** [comment]
I was thinking the 'sleep' section would go on there

**Comment by GentlemanHal** [comment]
Hmm, interesting.

Sleeping applies to specific projects so if we wanted to add it to the timing section we'd need to come up with a nice way that doesn't involve duplicating the tracking page.

**Comment by joejag** [comment]
About sleep we have is for the whole monitor to prevent screen burn

**Comment by GentlemanHal** [comment]
Ah, issue #71? I thought you meant issue #42

**Comment by GentlemanHal** [comment]
We could potentially use it for issue #42 as well by adding an auto complete dropdown box for choosing a build to snooze.

**Comment by joejag** [comment]
Yup, I meant both sleeps

**Comment by GentlemanHal** [comment]
You've convinced me, closing. Quickest issue ever!
