### ISSUE TITLE
If any tray fails while monitoring just an error is shown

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#76]
If you have added multiple trays, while monitoring if any of them is unavailable / broken then a 500 response is returned from the server.

It makes sense to show an error as the tray needs to be fixed, but how do we handle it?

If we continue to _just_ show the error then the Nevergreen API needs to be fixed to return more context, namely the tray that generated the error.

If we still want to show projects from working trays then we need to fix the Nevergreen API to be able to return projects and errors, and we need to fix the UI to show both correctly.

Thoughts?

**Comment by cowley05** [comment]
Maybe we could put the failing tray as a red build box? we could just use the url?

But yes we need to fix server to not just die too, i think it sometimes bombs out and wont come back when we have had our go server go down and i have had to restart and kill local storage.

**Comment by joejag** [comment]
paging @kornysietsma it would be good to get your input here.

**Comment by GentlemanHal** [comment]
I'm thinking even if we decide to just show an error on Nevergreen we should still fix the API to return projects for working trays. As that would make it a more useful API for others to consume.

**Comment by darrenhaken** [comment]
Starting to look at this - initially I'm going to stop an unavailable/broken tray from affecting the other trays.

Eventually, I'm going to look at returning different data in the tray JSON to indicate that the tray is unavailable. Thoughts?
