### ISSUE TITLE
Naming trays

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#77]
Instead of showing the url of the tray in the header a name should be shown instead.

If you are adding multiple trays it's likely they belong to a particular team or project so being able to name then accordingly is probably more helpful than the url which is mostly just a server name.

The url could be the default until the user changes it or we could potentially generate random names for added trays similar to how Heroku does for apps.

**Comment by joejag** [comment]
+1 Whether we randomly generate or default to the URL depends on the UX of
the edit tray name

**Comment by GentlemanHal** [comment]
Have implemented this with new trays getting random generated names. The name can be updated on the tray settings page and if it is removed the url will be shown in the title instead.

Let me know what you think.

**Comment by joejag** [comment]
Being able to set the name is a great feature. As @GentlemanHal says about non-obvious URLs inside a company.

I reckon the URL should be the default name. It's fun having a random name, but it's a bit confusing if you don't know what is going on.

**Comment by GentlemanHal** [comment]
> I reckon the URL should be the default name. It's fun having a random name, but it's a bit confusing if you don't know what is going on.

I agree with this, but on the flip side how many people will discover they can change the name in the settings? Maybe we could always have the url in the title bar as a sub title or something?

**Comment by joejag** [comment]
+1 random name plus URL works for me.

**Comment by barisbalic** [comment]
+1 random name, much more humane.  Also URL is good to see, could be a tooltip/hover jobby.

**Comment by GentlemanHal** [comment]
Done!
