### ISSUE TITLE
Split the front end and API into different repos?

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#79]
Pros:

- The UI and API can evolve independently (own version numbers etc).
- Makes it easier for people creating their own UIs as they can just run the API.
- We could scale out the API independently of the UI.
- We could host the UI directly from Node.
    - React can render the initial page request server side (has SEO benefits if nothing else).
- Can easily tune headers (caching etc) for the UI without effecting the API endpoints.
- Makes the project layouts simpler as they can become standard JS and Clojure projects.

Cons:

- Makes deployment more complicated.
- Running functional tests become more complicated.

Thoughts?

**Comment by cowley05** [comment]
I like the idea!

Could cause complications with cross origin requests too couldnt it?

Im willing to go with that idea if we can solve the cons easily...

**Comment by joejag** [comment]
It'd be great to hear how people are using Nevergreen. Are they on Heroku? Using the Docker image? Or straight java -jar? Knowing that would help me know if we want to do this split.

I like that we only depend on Java at runtime just now. You run one command to get an instance. 

For folks just making their own UI they can use our mvp monitor at: https://github.com/build-canaries/nevergreen/blob/master/doc/mvp-monitor.html

We could perhaps wrap the node output into some jetty static site thing. I'm not keen on asking our customers to install java and npm to run locally (unless java -jar isn't the number one way of running Nevergreen).

I'd like to suggest, for now, that we create two folders in our repo at the root. One for UI, the other for the server. We then have some script(s) at the top that build it into two wars? It'd clean things up a bit. And could be a prelude to splitting into different repos.

Alternatively, can we think of a way to find out about usage?

**Comment by GentlemanHal** [comment]
> It'd be great to hear how people are using Nevergreen

This is something I'm very curious about and is absolutely something we need to chat about Saturday.

If we don't plan on separating them at some point having the two root folders feels like it might be more complicated, so it's probably worth holding off on that idea until we talk about this some more?

An improvement that I already started is to separate the front end and API resources on the server, that way we can at add different middleware (caching, logging etc) to them.
