### ISSUE TITLE
Broken build timer

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#82]
Now we are using React to render the monitor view it should be possible to add a timer for broken builds showing how long they have been broken (hh:mm:ss or something similar just rendered under the name).

Like all options that make the monitor view more complicated it should be optional and off by default.

**Comment by jimmythompson** [comment]
I've made at start on this and currently have the following:

![nevergreen with timers](https://cloud.githubusercontent.com/assets/653864/11763291/4b6b4ec6-a0fc-11e5-9eb3-84555f8a86fd.png)

I'm currently stuck on where to put the toggle which turns it on and off, there doesn't seem a natural fit.

I'm toying with the idea of a new view, called Configure, with on/off toggles. This could evolve into something more elaborate, with a live preview, but that seems more appropriate when there's more than one thing to toggle.

Any ideas?

**Comment by joejag** [comment]
A separate config area makes sense to me too. 

It should just be toggling features of the dashboard view, so I think we should call it 'dashboard' or 'monitor options'.

I like the preview option too.

For this issue let's just add a timer (I'm happy with the concept shown by @jimmythompson) and a simple configuration area with just one checkbox to toggle the feature.

We can create new issues for the preview pane, and other things we discover.

Thoughts?

**Comment by GentlemanHal** [comment]
If this was configurable per tray, we already have tray settings it could be added too. However this doesn't feel like something you'd want to have on for some trays but not others?

If that is the case, then we are going to need a new top level section. So the problem is just coming up with a good name for it. 

My first thought was 'display', but that's probably because I play a lot of video games :stuck_out_tongue:  The main issue with that and your suggestions (configure, dashboard) is they are very generic and not really descriptive of what they contain. 'monitor options' is more descriptive but doesn't fit with the current naming, so I suspect it might not look very nice as it is that much longer.

I like the idea of a preview but it should definitely be done as a new issue.
