### ISSUE TITLE
Cross site AJAX requests don't work

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#84]
At the very least the MVP monitor no longer works.

```
mvp-monitor.html:1 XMLHttpRequest cannot load http://staging.nevergreen.io/api/projects/all. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 404.
```

It appears to be because an OPTIONS call is being done before the POST and this is getting rejected. I never checked the MVP monitor previously, but if it used to work correctly, then this was probably broken when the project calls were moved into the api namespace.

**Comment by joejag** [comment]
Oh bother, I thought this line fixed that issue:
https://github.com/build-canaries/nevergreen/blob/master/src/nevergreen/api/routes.clj#L9

Joe.
