### ISSUE TITLE
nevergreen.io can not be used over https

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#85]
**Mostly adding this issue for full transparency, and incase anyone reading has some alternative ideas of how to solve.**

As a work around `https://nevergreen.herokuapp.com/#/` can be used, but this still seems to generate a warning.

[StartSSL](https://www.startssl.com/) provides free class 1 certificates, but to use a custom domain with ssl on Heroku requires paying for the  [SSL add-on](https://addons.heroku.com/SSL).

**Comment by GentlemanHal** [comment]
Can this be closed?

**Comment by joejag** [comment]
yes :)
