### ISSUE TITLE
Passwords are exposed in request logs

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#87]
This is because all requests are logged as curl, which is very helpful for debugging. Currently we don't store any logs in files so these values are not persisted but anyone with access to the server could read recent passwords.

Possible solutions:

1. Stop logging requests as curl
2. Use a more involved logging framework
3. Check for passwords in logs and redact them

Solution 1 would make debugging issues in future much more difficult, but completely solves the issue.

Solution 2 means we could log enough at INFO level to know if and when requests are made while still logging them as curl at a DEBUG level. This would allow us to increase the logging level just to diagnose issues.

Solution 3 stops us having to mess about with logging frameworks but will be harder to maintain and means we wouldn't be able to solve problems that were caused by the data.

**Comment by GentlemanHal** [comment]
We currently use `clojure/tools.logging` which allows us to specify levels, but I'm not sure how to actually configure it in a nice way. It seems to just be a wrapper around existing Java loggers, so we'd probably have to explicitly add one and configure that underlying logger. 

This seems pretty horrible as I don't want to start adding external logging configuration files. [clj-logging-config](https://github.com/malcolmsparks/clj-logging-config) seems like it'll help move the configuration into code, but still seems to require a specific logging library. This means we'd have to deal with any headaches of getting all our dependencies using the correct framework (by adding slf4j bridges for example)

**Comment by joejag** [comment]
I'd favour S3. I'd like to hear more about why it would be a maintenance burden. In my simple world it's some fields we always overwrite when logging

S1 is easy, but makes it harder for us to develop and solve issues.
S2 involves the complexities of logging. Which I'd like to avoid if possible.

**Comment by GentlemanHal** [comment]
The maintenance I was referring to was simply having more [complicated] code.

We could no longer just use ring-curl to log all requests as curl if we wanted to redact passwords. I did write the ring-curl library so could potentially update that to allow passing a list of params to redact (not sure how hard that would be).
