### ISSUE TITLE
Add a toggle to show/mask password input when adding trays

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#88]
Usability enhancement.

http://www.lukew.com/ff/entry.asp?1941

**Comment by darrenhaken** [comment]
@GentlemanHal do you envision it working like the link you gave?

**Comment by GentlemanHal** [comment]
Yeah, pretty much.

We have an example of adding an icon to an input (for read-only inputs) so that would probably be the easiest solution. However that might be a little too subtle and adding the explicit show/hide password toggle might be a better idea.
