### ISSUE TITLE
Clear tray/message inputs once added

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#89]
When you add a new tray or success message (successfully) the inputs should be cleared automatically allowing another to be added easily.

**Comment by cowley05** [comment]
i have had a look at this as it seemed easy win (and was annoying me). Bit of React advise needed... I figured that best way to do this is to trigger an update of AddTray by changing the state back to initial state. this was the simplest way i found (and it works) but i didn't know if it was "good practise" also it doesn't allow us to clear it only on success of getting the tray - which i'm not sure is needed or not. 

Thoughts?

**Comment by GentlemanHal** [comment]
I think resetting the state is fine and the 'correct' way of changing it, but I don't know for sure as this is my only React experience.

Only clearing on success is interesting and something we should probably do for a nice UX. I think the simplest way would be to get the addTray/Message functions passed to React to return a promise.

```javascript
this.props.addTray(this.state).done(function () {
  this.setState({'whatever': ...})
})
```

**Comment by cowley05** [comment]
@GentlemanHal Had a quick look at that but it seems that success in this case would only be success of saving to local storage. As getting the projects isn't really related to adding the tray in any way.

Im not sure its worth the effort involved in doing this that way.

I think for now it would be fine to always clear on add?

**Comment by GentlemanHal** [comment]
Don't worry about this for now as its not a big deal (or planned into a milestone)

Also I don't like how this section currently loads projects anyway, so at some point I'd like to refactor, which might make this easier to implement.
