### ISSUE TITLE
Update username/password of existing trays

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen#90]
Users should be able to change the username and/or password of existing trays, including adding them even if they tray didn't need them originally.

This would save people having to completely reconfigure the tray (selecting included projects) for trays if something as simple as a password change was required.

**Comment by GentlemanHal** [comment]
Functionally this should be working correctly now. However the UX is a little poor as it's not obvious anything has happened. This is because I didn't want to just add the usual loading screen. Firstly because it is broken, see issue #106, and secondly I don't like how it's implemented in code.

I think we have the following choices:

1. Just add the existing loading screen.
2. Create some new feedback indicator for this, then use issue 106 to retrofit to other areas.
3. Close this and then use issue 106 to fix loading everywhere including here.
4. Automatically send the user back to the project list after they click update, which means the existing refresh feedback is used.

I currently learning towards option 4, thoughts?

**Comment by GentlemanHal** [comment]
I've implemented option 4, I think it works pretty well.

@joejag or @cowley05 are you able to give this a QA and close if you're happy?

**Comment by barisbalic** [comment]
Looks good, the visual feedback of having done the update is much nicer.
