### ISSUE TITLE
Show project stages as separate projects instead of combining them

### ISSUE THREAD

**Issue by elrob** [build-canaries/nevergreen#92]
Previously we were able to select which stages in the pipeline should be tracked in nevergreen (when using SNAP CI). Chris Martin thinks this was probably because SNAP CI pipelines were displaying each stage as a separate project (i.e. a bug). However, this was actually quite useful. It was possible using the checkboxes on the tracking tab. Each stage was a separate checkbox. However, there is now only one checkbox per project.

For example, when someone is configuring a new stage and we don't want the build to be red:

![screen shot 2015-07-14 at 13 33 15](https://cloud.githubusercontent.com/assets/3116850/8673259/e8582c28-2a2c-11e5-8823-3cfdd51f8618.png)

**Comment by cowley05** [comment]
Hi rob, thanks for logging the issue!

Just to make sure i understand, is the issue that you want to be able to select each stage to be tracked seperately? 
or is it that you want to be able to see what stage is currently running within a given pipeline?

**Comment by elrob** [comment]
Sort of. It would normally be that I want to toggle a trailing stage like the one in the screenshot so it is not included and doesn't cause the screen in front of my face to be red. (It's still red) :)

Previously (though it seems it was unintended) we were able to select each stage to be tracked separately. And we were therefore also able to see which stage was running in the pipeline.

Now we only have one checkbox and all the stages appear the same on the build monitor.

These are only small gripes though. I probably wouldn't have even thought of it except that the functionality used to be there (unintentionally). I'm a big fan of nevergreen.

**Comment by GentlemanHal** [comment]
This has been implemented and deployed to [staging](https://staging.nevergreen.io) as part of #101 

@elrob Can you test it out and let us know if it's working how you expect please?

**Comment by elrob** [comment]
Works a treat! 
The config suggests they are different 'projects' as opposed to 'stages' which might confuse others but the functionality is back to what we had a while back. Very nice!

**Comment by GentlemanHal** [comment]
@elrob Thanks for checking so quickly.

Your comment about calling them projects instead of stages is a very interesting and is actually a bigger discussion than you probably realise :smile: 

I'm having a hard time articulating why, but part of it comes down to having to deal with 3 different types of CI servers (Go, Snap and all the others) and naming in the entire codebase.
